INSERT INTO facilities (facilities_type) values ('Cryotherapy Chamber');
INSERT INTO facilities (facilities_type) VALUES ('Hyperbaric Oxygen Chamber');
INSERT INTO facilities (facilities_type) VALUES ('Indoor Rock Climbing Wall');
INSERT INTO facilities (facilities_type) VALUES ('Ninja Warrior Obstacle Course');
INSERT INTO facilities (facilities_type) VALUES ('Aerial Silks Studio');
INSERT INTO facilities (facilities_type) VALUES ('Floating Sensory Deprivation Tanks');
INSERT INTO facilities (facilities_type) VALUES ('Bouldering Wall');
INSERT INTO facilities (facilities_type) VALUES ('Anti-Gravity Treadmill');
INSERT INTO facilities (facilities_type) VALUES ('Infrared Sauna Pods');
INSERT INTO facilities (facilities_type) VALUES ('Virtual Reality Fitness Stations');
INSERT INTO facilities (facilities_type) VALUES ('Hypoxic Training Room (Simulated Altitude)');
INSERT INTO facilities (facilities_type) VALUES ('Aquatic Treadmills (Underwater Treadmills)');
INSERT INTO facilities (facilities_type) VALUES ('Aqua Cycling Pool');
INSERT INTO facilities (facilities_type) VALUES ('Biomechanics Lab');
INSERT INTO facilities (facilities_type) VALUES ('Gravity Resistance Training System');
INSERT INTO facilities (facilities_type) VALUES ('Electro Muscle Stimulation (EMS) Training');
INSERT INTO facilities (facilities_type) VALUES ('Mind-Body Meditation Pods');
INSERT INTO facilities (facilities_type) VALUES ('Biosensing Wearable Technology');
INSERT INTO facilities (facilities_type) VALUES ('Dynamic Resistance Technology');
INSERT INTO facilities (facilities_type) VALUES ('Kinesis Wall (Multi-Functional Movement Station)');
INSERT INTO facilities (facilities_type) VALUES ('Exergaming Zone (Interactive Fitness Games)');
INSERT INTO facilities (facilities_type) VALUES ('Acrobatic Yoga Facilities');
INSERT INTO facilities (facilities_type) VALUES ('Biosauna (Combining Biofeedback with Sauna)');
INSERT INTO facilities (facilities_type) VALUES ('Outdoor Calisthenics Park');
INSERT INTO facilities (facilities_type) VALUES ('Holographic Personal Trainer');
INSERT INTO facilities (facilities_type) VALUES ('Kinetic Energy-Harvesting Equipment');
INSERT INTO facilities (facilities_type) VALUES ('Rebounder Mini-Trampoline Area');
INSERT INTO facilities (facilities_type) VALUES ('Aromatherapy and Wellness Lounge');
INSERT INTO facilities (facilities_type) VALUES ('Parkour Training Space');
INSERT INTO facilities (facilities_type) VALUES ('Hiking/Trail Running Paths');
INSERT INTO facilities (facilities_type) VALUES ('Magnetic Resonance Therapy');
INSERT INTO facilities (facilities_type) VALUES ('AI-Powered Adaptive Training Programs');
INSERT INTO facilities (facilities_type) VALUES ('Mindful Movement Lab');
INSERT INTO facilities (facilities_type) VALUES ('Recovery Boots Stations');
INSERT INTO facilities (facilities_type) VALUES ('Hydration Stations with Infused Water');
INSERT INTO facilities (facilities_type) VALUES ('Neurofeedback Training Stations');
INSERT INTO facilities (facilities_type) VALUES ('Zorbing Ball Fitness');
INSERT INTO facilities (facilities_type) VALUES ('Brain-Computer Interface (BCI) Workouts');
INSERT INTO facilities (facilities_type) VALUES ('Climbing Rope Stations');
INSERT INTO facilities (facilities_type) VALUES ('Inversion Therapy Tables');
INSERT INTO facilities (facilities_type) VALUES ('Sensory Integration Room');
INSERT INTO facilities (facilities_type) VALUES ('Thermal Imaging for Muscle Activation');
INSERT INTO facilities (facilities_type) VALUES ('Solar-Powered Workout Stations');
INSERT INTO facilities (facilities_type) VALUES ('Energy-Generating Cardio Equipment');
INSERT INTO facilities (facilities_type) VALUES ('Gyrotonic Expansion System');
INSERT INTO facilities (facilities_type) VALUES ('Bike-Powered Charging Stations');
INSERT INTO facilities (facilities_type) VALUES ('Vibration Plate Training');
INSERT INTO facilities (facilities_type) VALUES ('Kinetic Sand Training Area');
INSERT INTO facilities (facilities_type) VALUES ('Aqua Bag Training Zone');
INSERT INTO facilities (facilities_type) VALUES ('Aerial Hammock Yoga Space');

INSERT INTO gym (name, address, year, website, contact_number) VALUES ('MilleniumGym', 'Strada Victoriei 12, București', 2008, 'http://www.milleniumgym.com', '0721123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyShapeGym', 'Bulevardul Unirii 45, Timișoara', 2019, 'http://www.bodyshapegym.net', '0731234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EnergymFitnessClub', 'Calea Dorobanților 87, Cluj-Napoca', 1997, 'http://www.energymfitnessclub.com', '0741345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('AmaltTraining', 'Strada Mihai Eminescu 23, Iași', 2010, 'http://www.amalttraining.org', '0751456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyTime', 'Bulevardul 1 Decembrie 1918 56, Brașov', 2016, 'http://www.bodytime-gym.com', '0761567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ClubFloreasca', 'Strada Avram Iancu 34, Constanța', 2002, 'http://www.clubfloreasca.ro', '0771678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('DairyFit', 'Aleea Trandafirilor 9, Craiova', 2018, 'http://www.dairyfit-fitness.com', '0781989012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('DumsilGYM', 'Bulevardul Decebal 78, Galați', 2005, 'http://www.dumsilgym.eu', '0791890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EnergiaFitnessCenter', 'Strada Aurel Vlaicu 2, Ploiești', 2015, 'http://www.energiafitnesscenter.com', '0701901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Fitclass', 'Bulevardul Republicii 101, Oradea', 1999, 'http://www.fitclass-gym.com', '0731012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GecoFitnessClub', 'Calea Aradului 67, Bacău', 2006, 'http://www.gecofitnessclub.net', '0741123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GriffGym', 'Strada Revoluției 5, Arad', 2012, 'http://www.griffgym.com', '0751234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('LibertyGym', 'Bulevardul Mihail Kogălniceanu 30, Sibiu', 2003, 'http://www.libertygym-fitness.com', '0761345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('MeiyoGym', 'Strada Ion Creangă 17, Brăila', 2011, 'http://www.meiyogym.com', '0771456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('NewFitWay', 'Aleea Soarelui 8, Baia Mare', 1998, 'http://www.newfitway-gym.com', '0781567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PTStudio', 'Calea Feldioarei 43, Buzău', 2007, 'http://www.ptstudio-fit.com', '0791678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PureShapes', 'Strada Ștefan cel Mare 21, Satu Mare', 2014, 'http://www.pureshapes-fitness.com', '0701789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SocialGym', 'Bulevardul Traian 11, Drobeta-Turnu Severin', 2004, 'http://www.socialgym.net', '0731890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SanaVivendi', 'Strada Cuza Vodă 14, Suceava', 2021, 'http://www.sanavivendi-gym.com', '0741901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('VivaSport', 'Aleea Ghioceilor 3, Târgu Mureș', 2012, 'http://www.vivasport-fitness.com', '0751012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SASGym', 'Bulevardul Iuliu Maniu 19, Focșani', 1998, 'http://www.sasgym.com', '0761123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WestlifeFitness&Aerobic', 'Strada Vasile Alecsandri 25, Pitești', 2007, 'http://www.westlifefitnessaerobic.org', '0771234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WorldGymAcademy', 'Strada 22 Decembrie 1989 4, Tulcea', 2014, 'http://www.worldgymacademy.com', '0781345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BambooFitness', 'Aleea Magnoliei 7, Resita', 2003, 'http://www.bamboofitness-gym.com', '0791456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('IzoconFitnessGym', 'Bulevardul Carol I 12, Deva', 2002, 'http://www.izoconfitnessgym.net', '0701567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Lady’sGym', 'Strada Calea Victoriei 3, Medgidia', 2005, 'http://www.ladysgym.com', '0731678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BigFitness', 'Calea Crângului 40, Bistrița', 2011, 'http://www.bigfitness-gym.com', '0741789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('RealBodyGym', 'Strada Aviatorilor 9, Zalău', 2007, 'http://www.realbodygym.com', '075189023');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EletroGYM', 'Bulevardul Eroilor 22, Slobozia', 2014, 'http://www.eletrogym.com', '0761901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FitnessClubRelaxsim', 'Strada Alexandru Sahia 14, Piatra Neamț', 2003, 'http://www.fitnessclubrelaxsim.org', '0771012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('MelodyBodySculpture', 'Calea Timișoarei 76, Călărași', 2002, 'http://www.melodybodysculpture-gym.com', '0781123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Piti’sCenter', 'Strada Mihai Bravu 18, Tecuci', 2005, 'http://www.pitiscenter.com', '0791234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('LIONSGYM', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2011, 'http://www.lionsgym.com', '0701345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('AresGymFortuna', 'Strada Pictor Nicolae Grigorescu 4, Mangalia', 2000, 'http://www.aresgymfortuna.net', '0731456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('TonicGym', 'Bulevardul Nicolae Bălcescu 2, Slatina', 2015, 'http://www.tonicgym-gym.com', '0741567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Lady’sFitGym', 'Calea Clujului 92, Alba Iulia', 1997, 'http://www.ladysfitgym.com', '0751678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ColosseumLady’s', 'Strada Mărășești 31, Giurgiu', 2019, 'http://www.colosseumladys.com', '0761789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyClubCasanova', 'Strada Alexandru Sahia 14, Piatra Neamț', 2006, 'http://www.bodyclubcasanova-gym.com', '0771890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('C.S.ProFitnessVulcan', 'Calea Timișoarei 76, Călărași', 2012, 'http://www.csprofitnessvulcan.com', '0781901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('JadeGym', 'Strada Mihai Bravu 18, Tecuci', 2003, 'http://www.jadegym.com', '0791012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FlexGym', 'Bulevardul Corneliu Coposu 5, Sighetu Marmației', 2011, 'http://www.flexgym-gym.com', '0701123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PerfectFit', 'Aleea Trifoiului 11, Vaslui', 2000, 'http://www.perfectfit-fitness.com', '0731234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ClubBlackKnightSquash&FitnessPloiesti', 'Strada Pictor Nicolae Grigorescu 4, Mangalia', 2005, 'http://www.clubblackknightploiesti.com', '0741345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GreenDiamond', 'Calea Rahovei 29, Adjud', 2011, 'http://www.greendiamond-fitness.com', '0751456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('4UFitnessCenter', 'Strada Nicolae Titulescu 8, Lugoj', 2000, 'http://www.4ufitnesscenter.com', '0761567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SportCenter', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2015, 'http://www.sportcenter-gym.com', '0771678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SmartFitStudio', 'Strada George Coșbuc 7, Săcele', 1997, 'http://www.smartfitstudio.net', '0781789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FitnessModelGym', 'Aleea Bradului 16, Gherla', 2006, 'http://www.fitnessmodelgym.com', '0791890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('HardcoreFitness', 'Calea Rahovei 29, Adjud', 2012, 'http://www.hardcorefitness-gym.com', '0709901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GymOne', 'Strada Nicolae Titulescu 8, Lugoj', 2003, 'http://www.gymone-fitness.com', '0731012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WorldClass', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2011, 'http://www.worldclass.com', '0741123456');